### ISSUE TITLE
360 Videos

### ISSUE THREAD

**Issue by r3a1d3a1** [yossato/virtualGimbal#8]
To what extent does this work for 360 videos?
If not too well, how would it be possible to adapt it for 360?
Thank you!

**Comment by yossato** [comment]
VirtualGimbal doesn't work for 360 videos since camera intrinsic parameter model doesn't support fish eye lens, and an usual 360 camera outputs dual sensor images into an image, i.g, side by side images. This is not supported by virtualgimbal. There are many issues to adapt it for 360.

**Comment by r3a1d3a1** [comment]
Thank you
